### PR TITLE
Discourse email response notification

### PR DESCRIPTION
**Pull request by kevinkid**
This is a reference to issue #1605 on tc-connect.

### CODE REVIEW

**Comment by gondzo** [comment]
@kevinkid nice work. Here are some details that need to be ironed out
1. We need only posts created via email, not all posts created on discourse
2. initWebhooks should be moved to discourse.js
3. No need for new event types in app/constants.js, use the POST_CREATED
4. move the `router.post('/v4/webhooks', webhookHandler);` down to `register all routes section
5. webhooks.js should filter the posts and emit event only for email posts
6. Do we need to always create the webhook on app start? What happens if the hook is already registered?
7. `webhookPayloadBaseUrl` should be defined for all environment files. in default.js it should be talk.topcoder-dev.com and in local.js you can set it as local.topcoder-dev.com
8. We need detailed logging - webhook created/failed (with details about the cause); webhook handler called; creating new event; failed processing webhook (with details), etc
9. `npm run lint` must show no errors

**Comment by kevinkid** [comment]
There isn't a way to filter the posts, we have to configure discourse web client to emit post events differently. That means we don't have to create webhooks.

**Comment by gondzo** [comment]
what's the alternative?

**Comment by kevinkid** [comment]
a longer route would be to use webhooks then filter duplicate notifications

**Comment by gondzo** [comment]
discourse post has a 'via_email' field that can be used for this purpose. so in the webhook we should call descourse.getPost to get post details and then create the event if via_email is true

**Comment by kevinkid** [comment]
Thanks, thats a nice way to filter events.

**Comment by kevinkid** [comment]
Its better if the webhook is already registered, i created it for testing purpose but i guess we can get rid of that endpoint.

**Pull request closed without merging**
