### PR TITLE
Elastic Search Indexing Capability for Topic/Post

### PR DESCRIPTION
**Pull request by rahulranjanmca**

### CODE REVIEW

**Comment by vikasrohit** [comment]
@gondzo @rahulranjanmca I have added the elastic search for circle ci build, but tests are failing on circle ci. Do you have idea about it? I am trying to fix them, but if you guys have idea, please let me know.

**Comment by rahulranjanmca** [comment]
I haven't seen the failing test, so cannot comment on that. What I saw is
circleci elasticsearch version and application elasticsearch version not
matching. Apart from that, test would expect to have the index already
created which is mentioned in config file. Can you make sure these two
thing are okay?

**Comment by vikasrohit** [comment]
Our cluster is at 2.3 version. So, may be we need to update the code to use old APIs.

However, even if can upgrade to the latest version, I tried it locally, it is still failing for me. If it is because of missing index in elastic search, we have to create that programatically because in CI we can do that manually.

**UPDATE:** It seems tests got passed on circle ci after upgrading the elastic search version for circle ci. However, these are failing on my local, may be data is inconsistent on my local.
@rahulranjanmca Can we downgrade the changes to use elastic search 2.3?

**Comment by gondzo** [comment]
@vikasrohit any plans for upgrading the cluster? are we using it only for message service or it is shared ?

**Comment by vikasrohit** [comment]
Right now the ES cluster is shared for different indexes like members, projects etc. And I think it makes sense to use the same cluster for messaging as well, though we can instantiate a new cluster for messaging.

**Comment by vikasrohit** [comment]
@gondzo Do you think we would be able to downgrade the cluster to 2.3? I have checked on the production and we don't have any cluster which is running on > 2.3.

**Comment by vikasrohit** [comment]
Closing the PR as we are not downgrading the ES cluster now and already merged the Elastic Search changes via #69

**Pull request closed without merging**
