### PR TITLE
fix migrations scripts

### PR DESCRIPTION
**Pull request by maxceem**
During deploying this repo locally I've installed the `sequelize-cli` and when I run `NODE_ENV=development sequelize db:migrate` I got the error 
```
ERROR: Migration 20160718175721-initial.js (or wrapper) didn't return a promise
```
see full output:
image

It looks like some time ago underlying dependency `umzug` of `sequelize-cli` has been updated and now it requires us to always return promises in `up` and `down` functions, see related issue https://github.com/sequelize/umzug/issues/185

After this fix, the migrations scripts work well:
image

### CODE REVIEW

**Comment by vikasrohit** [comment]
Looks good to me. Only query is that can the issue you faced on your local, was because of version of the installed sequelize? I mean if you downgrade your local sequelize, does the error go away?

**Comment by maxceem** [comment]
> Only query is that can the issue you faced on your local, was because of version of the installed sequelize?
I think yes, because I've just installed it today during local deploying.

> I mean if you downgrade your local sequelize, does the error go away?

I didn't try to downgrade it as I'm not sure which version has been used before. But I think if the updated script works for you than it looks like the update should support both versions.

**Comment by vikasrohit** [comment]
Yes, that is true. I would try that. Btw, the version of your sequelize cli matches with version we are using in the service itself?

**Comment by vikasrohit** [comment]
I am merging the PR for now, and will test it on my local later on and if somehow it does not work with the sequelize version I am having, we can take a look at it again.

**Comment by maxceem** [comment]
Hmm, no it doesn't. I use the latest `sequelize-cli 5.4.0` while in the dev dependencies there is `2.4.0`.

I've just noticed, that we have scripts in the package to run the migrations using project verision of `sequalize-cli` https://github.com/appirio-tech/tc-message-service/blob/dev/package.json#L28-L29.

But in README it proposes to use commands which will use globally installed version: 
image

So alternatively, we can revert this PR, and updated README to not get confused regarding versions.

**Pull request merged**
