### PR TITLE
Improve check permission method debug

### PR DESCRIPTION
**Pull request by maxceem**
I've noticed that currently, non-admin users cannot get topics using `/topics/list` endpoint on DEV. This is most likely due to latest changes https://github.com/appirio-tech/tc-message-service/pull/100.

I don't see any reason by code for this. So I've refactored method to check permissions and added more debug output to it, so we would know what exactly was the reason for denying access.

Also, I've fixed some implicit error if the referenceLookup is not found.

### CODE REVIEW

**Comment by vikasrohit** [comment]
Thanks @maxceem for better error handling for missing referenceLookup record. However, I think if it was error because of this common helper method, it would have occurred for all endpoint, isn't it?

**Comment by maxceem** [comment]
> Thanks @maxceem for better error handling for missing referenceLookup record. However, I think if it was error because of this common helper method, it would have occurred for all endpoint, isn't it?

It's just very strange error which I see now, and I don't have an idea how it could happen at the moment. So I've added this debug, so we can make it clear where is it.

**Comment by vikasrohit** [comment]
Okay. Let me know if you need any help from my side for this.

**Comment by maxceem** [comment]
I've just tried to load posts using `pshah_customer` use in this project http://local.topcoder-dev.com:3000/projects/8049/

But all requests return 403 for URLs like `https://api.topcoder-dev.com/v5/topics/list/db?filter=reference%3Dproject%26referenceId%3D8049%26tag%3Dphase%235302`.

Could you please have a looks what is there in the debug output of the message service.

**Comment by maxceem** [comment]
Same for Dashboard posts: `https://api.topcoder-dev.com/v5/topics/list/db?filter=reference%3Dproject%26referenceId%3D8049%26tag%3DPRIMARY`

**Pull request merged**
