### PR TITLE
issue 3031 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by maxceem** [comment]
@vikasrohit I've tested this fix for https://github.com/appirio-tech/connect-app/issues/3031 locally. And it works good for me. I propose to merge it to DEV, deploy and verify one more time on the DEV environment.

**Review by vikasrohit — APPROVED** [review]
I think we would just the return the promise of `db.post_attachments.update`, it would result in the same behaviour. However, I guess async-await makes it bit more intuitive. So, approving the PR to be merged into dev.

**Comment by vikasrohit** [comment]
@maxceem merged the PR, please let me know your verification results in dev.

**Comment by maxceem** [comment]
@vikasrohit I've tested on DEV and this fix works good. There is still some issue in Connect, but it's no because of the backend this time.

**Pull request merged**
